FROM mcr.microsoft.com/dotnet/sdk:6.0 as builder
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Development

COPY ./IdentityServer/IdentityServer.csproj ./Server/IdentityServer.csproj
WORKDIR ./Server
RUN dotnet restore
COPY ./IdentityServer .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
ENV ASPNETCORE_ENVIRONMENT Development
ENV ASPNETCORE_URLS http://+
ENV ASPNETCORE_HTTP_PORT 81
WORKDIR /app
COPY --from=builder /app/Server/out ./Server/
WORKDIR ./Server
CMD dotnet IdentityServer.dll
